### ISSUE TITLE
Issue with sample data 

### ISSUE THREAD

**Issue by kshtjkumar** [alexhang212/YOLO_Behaviour_Repo#1]
Hi i cudnt find the sample data and when i run the command :
`python Code/3_VisualizeResults.py --Video "./Data/JaySampleData/Jay_Sample.mp4" --Weight  "./Data/Weights/JayBest.pt" --Start 0 --Frames -1`

but got an error :
```
Traceback (most recent call last):
  File "Code/3_VisualizeResults.py", line 87, in <module>
    model = YOLO(WeightPath)
  File "/Users/kshitijkumar/miniconda3/envs/YOLO/lib/python3.8/site-packages/ultralytics/engine/model.py", line 93, in __init__
    self._load(model, task)
  File "/Users/kshitijkumar/miniconda3/envs/YOLO/lib/python3.8/site-packages/ultralytics/engine/model.py", line 139, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/Users/kshitijkumar/miniconda3/envs/YOLO/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 622, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/Users/kshitijkumar/miniconda3/envs/YOLO/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 561, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/Users/kshitijkumar/miniconda3/envs/YOLO/lib/python3.8/site-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/kshitijkumar/miniconda3/envs/YOLO/lib/python3.8/site-packages/torch/serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/kshitijkumar/miniconda3/envs/YOLO/lib/python3.8/site-packages/torch/serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Data/Weights/JayBest.pt'
```

**Comment by alexhang212** [comment]
Hello,

Sorry, the readme was not fully updated. You will have to download the sample dataset here ( https://doi.org/10.17617/3.EZNKYV), and paste the folder inside the "Data/" folder. Also make sure you current working directory is under YOLO_Behaviour_Repo/ (using 'cd Path/To/YOLO_Behaviour_Repo')

Alex
